title: Iti Shree
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Iti Shree
avatar: /logo.png
email: itishree1999@gmail.com
skin: sunrise
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: nmdis_iti
  card: summary
logo: logo.png
social:
  name: Iti Shree
  links:
    - https://twitter.com/nmdis_iti
    - https://www.facebook.com/iti.shree.1420/
    - https://github.com/iShree20
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
